name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup FluentCI
        uses: fluentci-io/setup-fluentci@v5
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install rebar3
        run: |
          curl -o rebar3 https://s3.amazonaws.com/rebar3/rebar3
          chmod +x rebar3
          sudo mv rebar3 /usr/local/bin/
      - name: gleam test
        run: |
          fluentci run --wasm gleam test
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: gleam build
        run: |
          fluentci run --wasm gleam build
